package broker

import (
	"fmt"
	"os"
	"strings"
	"testing"
)

// Keep the complete user-facing examples backed by renderers, including the
// permission keyboard, route line and status examples beyond Held/eviction.
// Fragments with ellipses in the prose are diagnostic prefixes, not full notices.
func TestDocsQuoteAllNoticeExamples(t *testing.T) {
	clearFetchTestEnvironment(t)
	b := newTestBroker(t, mfWithTelegram())
	t.Cleanup(b.Shutdown)
	read := func(path string) string {
		t.Helper()
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		return string(data)
	}
	readme := read("../../README.md")
	usage := read("../../docs/USAGE.md")
	keyboard := permKeyboard("abcde")
	permission := permPromptText("Bash", "git push origin fix/flaky-test") + "\n\n[" + keyboard[0][0].Text + "] [" + keyboard[0][1].Text + "]"
	global := strings.Replace(b.statusGlobal(), fmt.Sprintf("(pid %d)", os.Getpid()), "(pid 12345)", 1)
	// The Markdown example's two-space indent is presentation, not output.
	global = strings.ReplaceAll(global, "\n", "\n  ")
	for _, tc := range []struct{ doc, text string }{
		{readme, permission},
		{readme, heldReplyText("telegram", 1)},
		{readme, heldDegradedText()},
		{usage, heldReplyText("telegram", 1)},
		{usage, b.statusForTopic("telegram", -100, nil)},
		{usage, global},
		{usage, evictionNotice(1, 0, 1, nil, true)},
		{usage, evictionNotice(0, 1, 1000, nil, true)},
	} {
		if !strings.Contains(tc.doc, tc.text) {
			t.Errorf("docs omit or alter actual notice:\n%s", tc.text)
		}
	}
	// The auto-update advisory is generated by the real sender and compared with
	// the quoted version placeholder, without invoking the updater or a daemon.
	fc := &fakeChannel{}
	withChannel := brokerWithChannel(t, mfWithTelegram(), fc)
	t.Cleanup(withChannel.Shutdown)
	key := MakeRouteKey("telegram", -100, nil)
	stub := withChannel.Stubs.Register("claude", os.Getpid(), "/work", nil)
	withChannel.Routes.Claim(key, stub)
	withChannel.notifyUpdateRestart("vX")
	replies := fc.sendRepliesSnapshot()
	if len(replies) != 1 || !strings.Contains(usage, replies[0].Text) {
		t.Fatalf("auto-update example=%+v", replies)
	}
	for _, stale := range []string{"Auto-attached to 'foo'", "no phase-5 flap timer", "The queue earns its keep only when", "which *consumes* the messages"} {
		if strings.Contains(readme+usage, stale) {
			t.Errorf("stale notice/contract: %s", stale)
		}
	}
}
