"""Frozen raw -> production extraction -> verdict, before and after export.

No fixtures, expectations, classifications, or verdicts are generated by tests.
The third path runs in a fresh interpreter, with no access to redaction maps.
"""
from copy import deepcopy
import hashlib
import inspect
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch

from capture_context import load_capture
from collect import build_verdict_inputs, capture_observation, classify, classify_fetch, fetch_trailer, result_text
from host import checked_read
from matrix import Cell
from replay_export import export_replay_capture
import replay_fixture_support
from verdict_core import evaluate, derive

ROOT = Path(__file__).parent / 'testdata/extractor-replay'
PASS = dict(status='PASS', reasons=[], not_evaluated=[])
INCOMPLETE = 'evidence collection incomplete'
ONCE = 'host did not receive each source exactly once'
TRAILER = 'fetch tool result lacks the complete matching receipt trailer'
IDENTITY = 'delivery evidence identity mismatch'


def read_json(path):
    return json.loads(path.read_text())


def events(observation, milestone):
    return [event for event in observation['events'] if event['milestone'] == milestone]


def semantic(observation):
    """Only byte-representation digests differ. Every other field is compared."""
    value = deepcopy(observation)
    for artifact in value['artifacts']:
        artifact['content_digest'] = None
    return value


def fresh_replay(root):
    code = ('import json,sys; from capture_context import load_capture; '
            'r=load_capture(sys.argv[1]); '
            'print(json.dumps({k:r[k] for k in ("inputs","evidence","classifications","diagnostics")}))')
    result = subprocess.run([sys.executable, '-c', code, str(root)], cwd=Path(__file__).parent,
                            text=True, capture_output=True, check=True)
    return json.loads(result.stdout)


class ExtractorReplayTests(unittest.TestCase):
    maxDiff = None

    def assert_bad_identity(self, name, root, replay):
        """Check the bad canonical claim before evaluating its named failure."""
        observation = replay['inputs'][2]
        if name.startswith('occurrence-'):
            claim = read_json(root/'mutation.json')['identity']
            raw = (root/claim['file']).read_text()
            if claim['line'] is not None:
                raw = raw.splitlines()[claim['line']-1]
            if claim['file'].endswith(('.json', '.jsonl')):
                raw = json.loads(raw)
            for key in claim['path']:
                raw = raw[key]
            if claim['contains']:
                self.assertIn(claim['bad'], raw)
            else:
                self.assertEqual(raw, claim['bad'])
            if 'milestone' in claim:
                event = events(observation, claim['milestone'])[0]
                value = event
                for key in claim['canonical_path']:
                    value = value[key]
                self.assertEqual(value, claim['bad'])
                self.assertFalse(event['collection_complete'])
            if 'absent' in claim:
                self.assertFalse(events(observation, claim['absent']))
            diagnostics = [item for item in replay['diagnostics'] if item['code'] ==
                           'delivery evidence identity mismatch: '+claim['field']+' correlation conflict']
            self.assertTrue(diagnostics)
            self.assertTrue(all(item['locator'].startswith('line:') for item in diagnostics))
            self.assertFalse(observation['collection_complete'])
            if name in ('occurrence-channel-attempt', 'occurrence-inbox-attempt'):
                record = json.loads((root/'records.jsonl').read_text().splitlines()[1])
                extracted = classify(record)
                self.assertTrue(extracted['accept'])
                self.assertEqual(extracted['attempt'], claim['bad'])
                binding = next(json.loads(v) for v in (root/'context/attempts.jsonl').read_text().splitlines()
                               if json.loads(v)['artifact_id']=='host-records' and json.loads(v)['line']==2)
                self.assertNotEqual(binding['attempt_id'], extracted['attempt'])
                self.assertEqual(derive(*replay['inputs'])['received']['41001'], 0)
            if name == 'occurrence-persisted-source':
                persisted = events(observation,'row_persisted')
                self.assertEqual([e['members'][0]['source_ids'] for e in persisted],[['41001'],['41002']])
                self.assertEqual(persisted[0]['members'][0]['row_id'],persisted[1]['members'][0]['row_id'])
                self.assertEqual(persisted[0]['members'][0]['revision'],persisted[1]['members'][0]['revision'])
            return
        terminal = events(observation, 'attempt_terminal')
        host = events(observation, 'transcript_recorded')
        receipt = events(observation, 'receipt_accepted')
        reserved = events(observation, 'attempt_reserved')
        if name == 'wrong-terminal-token':
            self.assertEqual(terminal[0]['token'], 'token-terminal-wrong')
            self.assertEqual(terminal[0]['attempt_id'], reserved[0]['attempt_id'])
            self.assertEqual(terminal[0]['group_id'], reserved[0]['group_id'])
            self.assertNotEqual(terminal[0]['token'], reserved[0]['token'])
        elif name == 'wrong-host-session':
            self.assertEqual(host[0]['scope']['host_session_id'], 'session-host-wrong')
            self.assertNotEqual(host[0]['scope']['host_session_id'], replay['inputs'][0]['host_session_id'])
            self.assertEqual(derive(*replay['inputs'])['received']['41001'], 0)
        elif name == 'misattributed-transcript':
            self.assertTrue(any('ownership conflict' in item['code'] for item in replay['diagnostics']))
            self.assertEqual(next(stream for stream in observation['streams'] if stream['id']=='host')['scope']['host_session_id'], 'session-host-wrong')
            self.assertEqual(host[0]['scope']['host_session_id'], 'session-host-original')
        elif name in ('wrong-broker-session', 'reused-pid-different-epoch', 'wrong-terminal-epoch'):
            observed = terminal[0] if name == 'wrong-terminal-epoch' else receipt[0]
            key, expected = ('session_id','session-broker-wrong') if name=='wrong-broker-session' else ('connection_epoch_id','epoch-other')
            self.assertEqual(observed['scope'][key], expected)
            self.assertNotEqual(observed['scope'][key], reserved[0]['scope'][key])
            if name=='reused-pid-different-epoch':
                owners=read_json(root/'context/ownership.json')['owners']
                self.assertEqual({row['pid'] for row in owners},{45671})
        elif name=='duplicate-host-delivery':
            copies=[event for event in host if event['members'][0]['source_ids']==['41001']]
            self.assertEqual(len(copies),2)
            self.assertEqual(len({event['delivery_id'] for event in copies}),2)
            self.assertEqual(len({event['payload']['host_record_id'] for event in copies}),2)
        elif name=='duplicate-source-replacing-another':
            self.assertEqual([event['members'][0]['source_ids'] for event in host],[['41001'],['41001']])
            self.assertEqual([event['members'][0]['row_id'] for event in host],['row-original-1','row-original-2'])
            self.assertEqual((root/'records.jsonl').read_text().count('MATRIX_SAMPLE'),2)
        elif name=='stale-retired-revision':
            self.assertEqual(terminal[0]['payload']['retired_members'][0]['revision']['value'],'a'*64)
            persisted=events(observation,'row_persisted')[-1]
            self.assertEqual(persisted['members'][0]['revision']['value'],'c'*64)
            self.assertLess(persisted['position']['time_ms'],terminal[0]['position']['time_ms'])
        elif name=='wrong-retired-row':
            self.assertEqual(terminal[0]['payload']['retired_members'][0]['row_id'],'row-other')
            self.assertNotEqual(terminal[0]['payload']['retired_members'][0]['row_id'],reserved[0]['members'][0]['row_id'])
            self.assertEqual(len(terminal[0]['payload']['retired_members']),len(reserved[0]['members']))
        elif name in ('wrong-recorded-fetch-token','wrong-held-response-token','wrong-recorded-fetch-row','stale-host-revision','duplicate-fetch-row'):
            produced=events(observation,'fetch_result_produced')
            raw_host=[json.loads(line) for line in (root/'records.jsonl').read_text().splitlines()][2]
            candidate=fetch_trailer(result_text(raw_host['message']['content'][0]['content']))
            self.assertFalse(events(observation,'fetch_result_recorded'))
            self.assertTrue(any(item['code']=='fetch candidate rejected' for item in replay['diagnostics']))
            if name=='wrong-held-response-token':
                self.assertEqual(produced[0]['token'],'token-held-wrong')
                self.assertNotEqual(produced[0]['token'],reserved[0]['token'])
                self.assertNotEqual(candidate['token'],produced[0]['token'])
                self.assertTrue(any(item['code']=='held response reservation correlation rejected' for item in replay['diagnostics']))
            elif name=='wrong-recorded-fetch-token':
                self.assertEqual(candidate['token'],'token-recorded-wrong')
                self.assertNotEqual(candidate['token'],produced[0]['token'])
            elif name=='wrong-recorded-fetch-row':
                self.assertEqual(candidate['members'][0]['record_id'],'row-recorded-wrong')
                self.assertNotEqual(candidate['members'][0]['record_id'],produced[0]['members'][0]['row_id'])
            elif name=='stale-host-revision':
                self.assertEqual(candidate['members'][0]['revision'],'c'*64)
                self.assertNotEqual(candidate['members'][0]['revision'],produced[0]['members'][0]['revision']['value'])
            else:
                self.assertIsNone(candidate)

    def test_frozen_three_paths(self):
        roots = sorted(ROOT.glob('healthy-*')) + sorted((ROOT/'mutations').iterdir())
        self.assertGreaterEqual(len(roots), 45)
        for root in roots:
            with self.subTest(capture=root.name):
                replay = load_capture(root)
                self.assert_bad_identity(root.name,root,replay)
                expected_observation=read_json(root/'expected-observation.json')
                expected_result=read_json(root/'expected-result.json')
                self.assertEqual(replay['inputs'][2],expected_observation)
                self.assertEqual(replay['diagnostics'],read_json(root/'expected-diagnostics.json'))
                self.assertEqual(replay['classifications'],read_json(root/'expected-classifications.json'))
                raw_result=evaluate(*replay['inputs'])
                self.assertEqual(raw_result,expected_result)
                self.assertEqual(replay['inputs'][2]['provenance']['kind'],'raw_replay')
                self.assertEqual(replay['inputs'][2]['setup_errors'],[])
                if root.name.startswith('healthy'):
                    self.assertEqual(raw_result,PASS)
                    self.assertTrue(replay['inputs'][2]['collection_complete'])
                else:
                    mutation=read_json(root/'mutation.json')
                    self.assertEqual(raw_result['status'],'FAIL')
                    for reason in mutation['required_reasons']:
                        self.assertIn(reason,raw_result['reasons'])
                    self.assertEqual(replay['inputs'][0],load_capture(ROOT/mutation['base'])['inputs'][0])
                if (root/'mutation.json').exists():
                    mutation=read_json(root/'mutation.json')
                    for change in mutation['changes']:
                        before=(ROOT/mutation['base']/change['file']).read_bytes()
                        after=(root/change['file']).read_bytes() if (root/change['file']).exists() else None
                        self.assertNotEqual(before,after)
                        self.assertEqual(hashlib.sha256(before).hexdigest(),change['before'])
                        self.assertEqual(hashlib.sha256(after).hexdigest() if after is not None else None,change['after'])
                with tempfile.TemporaryDirectory() as directory:
                    exported=export_replay_capture(replay,Path(directory))
                    canonical=read_json(Path(directory)/'verdict-inputs.json')
                    self.assertEqual(evaluate(**canonical),raw_result)
                    exported_diagnostics=exported['diagnostics']
                    exported_classifications=exported['classifications']
                    del exported
                    sanitized=fresh_replay(Path(directory))
                    self.assertEqual(evaluate(*sanitized['inputs']),raw_result)
                    self.assertEqual(sanitized['diagnostics'],exported_diagnostics)
                    self.assertEqual(sanitized['classifications'],exported_classifications)
                    self.assertEqual(sanitized['inputs'][:2],[canonical['scenario'],canonical['contract']])
                    self.assertEqual(semantic(sanitized['inputs'][2]),semantic(canonical['observation']))
                    self.assertEqual(sanitized['evidence'],read_json(Path(directory)/'summary.json'))
                    # Classification locators and outcomes are part of the replay contract.
                    self.assertEqual([(v['locator'],v['accept']) for v in sanitized['classifications']],
                                     [(v['locator'],v['accept']) for v in replay['classifications']])
                    left=derive(**canonical); right=derive(*sanitized['inputs'])
                    self.assertEqual(left,right)

    def test_healthy_members_occurrences_and_milestones(self):
        channel=load_capture(ROOT/'healthy-channel-double')
        observation=channel['inputs'][2]
        reservations=events(observation,'attempt_reserved')
        self.assertEqual(len({v['token'] for v in reservations}),2)
        self.assertEqual([v['source_id'] for v in observation['sources']],['41001','41002'])
        self.assertEqual({member['row_id'] for v in reservations for member in v['members']},{'row-original-1','row-original-2'})
        for receipt,terminal in zip(events(observation,'receipt_accepted'),events(observation,'attempt_terminal')):
            self.assertLess(receipt['position']['time_ms'],terminal['position']['time_ms'])
        repeated=load_capture(ROOT/'healthy-channel-repeated')
        self.assertEqual(events(repeated['inputs'][2],'transcript_recorded'),events(observation,'transcript_recorded'))
        self.assertEqual(derive(*repeated['inputs'])['received'],{'41001':1,'41002':1})
        inbox=load_capture(ROOT/'healthy-inbox-single')
        self.assertEqual(len(events(inbox['inputs'][2],'transcript_recorded')),1)
        fetch=load_capture(ROOT/'healthy-fetch-double')
        o=fetch['inputs'][2]
        request,produced,recorded,accepted,retired=[events(o,m)[0] for m in
            ('fetch_requested','fetch_result_produced','fetch_result_recorded','receipt_accepted','attempt_terminal')]
        release=next(e for e in o['events'] if e['payload'].get('state')=='fetch_response_released')
        self.assertEqual([v['position']['time_ms'] for v in (request,produced,release,recorded,accepted,retired)],[180,220,240,250,270,280])
        self.assertEqual({v['operation_id'] for v in (request,produced,recorded,accepted,retired)},{'call-original'})
        self.assertEqual(len(next(s for s in o['queue_snapshots'] if s['barrier_id']=='fetch_result_held')['rows']),2)
        self.assertEqual(next(s for s in o['queue_snapshots'] if s['barrier_id']=='final')['rows'],[])
        permuted=load_capture(ROOT/'healthy-fetch-permuted')
        self.assertEqual(events(permuted['inputs'][2],'fetch_result_recorded'),[recorded])
        for replay in (channel,repeated,inbox,fetch,permuted):
            self.assertEqual(evaluate(*replay['inputs']),PASS)

    def test_cutoff_diagnostics_and_completeness(self):
        for name, barrier_id, line, cutoff in (('short-final-cut','final',6,4),
                ('short-injection-cut','injection',4,4),('short-held-cut','fetch_result_held',6,4),
                ('early-final-cut','final',6,2)):
            with self.subTest(capture=name):
                root=ROOT/'mutations'/name
                raw=json.loads((root/'context/driver.jsonl').read_text().splitlines()[line-1])
                self.assertEqual(next(c['seq'] for c in raw['cuts'] if c['stream_id']=='host'),cutoff)
                replay=load_capture(root)
                observation=replay['inputs'][2]
                self.assertEqual(next(s['last_seq'] for s in observation['streams'] if s['id']=='host'),3)
                barrier=next(b for b in observation['barriers'] if b['id']==barrier_id)
                self.assertFalse(barrier['collection_complete'])
                self.assertFalse(observation['collection_complete'])
                self.assertIn(dict(artifact_id='state',locator=f'line:{line}',code=
                    'final cut does not cover observed stream extent' if name=='early-final-cut' else
                    'stream cutoff outside observed extent'),replay['diagnostics'])
                self.assertIn(INCOMPLETE,evaluate(*replay['inputs'])['reasons'])

    def test_occurrence_audit_covers_identity_domains(self):
        claims=[read_json(p/'mutation.json')['identity'] for p in (ROOT/'mutations').glob('occurrence-*')]
        self.assertGreaterEqual(len(claims),36)
        self.assertEqual({c['field'] for c in claims}, {'attempt_id','group_id','token','transport','host_session_id',
            'session_id','run_id','route_id','connection_epoch_id','claim_generation','source_ids','members',
            'operation_id','request_id','host_record_id','artifact_id'})

    def test_no_context_cannot_create_completeness_and_live_rejects_synthetic(self):
        replay=load_capture(ROOT/'healthy-channel-double')
        context=replay['context']; descriptor=context.descriptor
        cell=Cell(**descriptor['cell'])
        observation=capture_observation(cell,replay['evidence'],context.reads['broker'],context.reads['adapter'],
            context.reads['host-records']['records'],context.reads['host-records'])
        self.assertIn(INCOMPLETE,evaluate(*build_verdict_inputs(cell,replay['evidence'],raw_observation=observation))['reasons'])
        forbidden=[{'events':[]},{'observation':replay['inputs'][2]},replay['inputs'][2],{'verdict':'PASS'},
                   {'collection_complete':True},{'rows_final':0},{'members':2}]
        for value in forbidden:
            o=capture_observation(cell,replay['evidence'],context.reads['broker'],context.reads['adapter'],[],capture_context=value)
            self.assertIn(INCOMPLETE,evaluate(*build_verdict_inputs(cell,replay['evidence'],raw_observation=o))['reasons'])
            self.assertIn('canonical input forbidden',o['streams'][0]['detail'])
        live=load_capture(ROOT/'healthy-channel-double',live=True)
        self.assertIn(INCOMPLETE,evaluate(*live['inputs'])['reasons'])
        self.assertTrue(any('synthetic context forbidden' in d['code'] for d in live['diagnostics']))
        # A live collector does not read context paths smuggled into aggregate evidence.
        from collect import collect
        with tempfile.TemporaryDirectory() as directory:
            output=Path(directory)
            result=collect(cell,None,output,output/'report',dict(capture_context=str(ROOT/'healthy-channel-double')))
            self.assertIn(INCOMPLETE,result['reasons'])

    def test_checked_failures_and_exact_locators(self):
        with tempfile.TemporaryDirectory() as directory:
            path=Path(directory)/'records.jsonl'
            path.write_bytes(b'broken\n[]\n{"type":"user"}')
            captured=checked_read(path,jsonl=True)
            self.assertEqual(captured['state'],'malformed')
            self.assertEqual(captured['problems'],['line:1: malformed JSON object','line:2: malformed JSON object','line:3: unterminated tail'])
            with patch.object(Path,'read_bytes',side_effect=PermissionError):
                self.assertEqual(checked_read(path)['state'],'unreadable')
        for name,expected in [('missing-broker','missing'),('malformed-broker-integer','malformed'),('truncated-broker-line','truncated'),('truncated-broker-suffix','truncated')]:
            r=load_capture(ROOT/'mutations'/name)
            self.assertEqual(next(s for s in r['inputs'][2]['streams'] if s['id']=='broker')['state'],expected)
        for name in ('malformed-broker-integer','malformed-broker-field'):
            r=load_capture(ROOT/'mutations'/name)
            self.assertTrue(any(d['artifact_id']=='broker' and d['locator'] in ('line:3','line:4') and 'malformed recognized TEST ATTEMPT' in d['code'] for d in r['diagnostics']))
        for name in ('missing-host','missing-held'):
            r=load_capture(ROOT/'mutations'/name)
            self.assertFalse(events(r['inputs'][2],'fetch_result_recorded'))
            if name=='missing-held':
                self.assertFalse(events(r['inputs'][2],'fetch_result_produced'))
        for name in ('rejected-peer-prefix','rejected-peer-provenance'):
            r=load_capture(ROOT/'mutations'/name)
            self.assertFalse(events(r['inputs'][2],'transcript_recorded'))
            self.assertEqual(r['evidence']['received'],{'41001':1})
            self.assertEqual(derive(*r['inputs'])['received'],{'41001':0})

    def test_malformed_context_is_schema_valid_incomplete(self):
        cases=[('context/ownership.json',dict(owners=2)),('context/rows.jsonl',dict(row_id=3,revision=False,source_ids=2)),
               ('context/attempts.jsonl',dict(artifact_id='broker',line='three',members=2)),
               ('context/receipts.jsonl',dict(action='accepted',elapsed_ms='invalid')),
               ('context/queue-samples.jsonl',dict(rows=0,collection_complete=True)),
               ('context/contracts.jsonl',dict(negotiation='v1',channel='true')),
               ('context/driver.jsonl',dict(action='cut',cuts=True)),
               ('context/injection.json',dict(message_ids=[True],broker_lines=[1],kind='text')),
               ('capture.json',dict(events=[],observation={},verdict='PASS'))]
        for file,value in cases:
            with self.subTest(file=file), tempfile.TemporaryDirectory() as directory:
                root=Path(directory)/'capture';shutil.copytree(ROOT/'healthy-channel-double',root)
                (root/file).write_text(json.dumps(value)+'\n')
                # Preserve the old seal: malformed parsing must survive an extent failure too.
                r=load_capture(root)
                result=evaluate(*r['inputs'])
                self.assertEqual(result['status'],'FAIL')
                self.assertIn(INCOMPLETE,result['reasons'])
                self.assertFalse(any(reason.startswith('invalid input:') for reason in result['reasons']))
                self.assertTrue(r['diagnostics'])

    def test_principal_arguments_cannot_be_overwritten_by_context(self):
        replay=load_capture(ROOT/'healthy-channel-double')
        context=replay['context']
        with tempfile.TemporaryDirectory() as directory:
            path=Path(directory)/'broker.log'
            path.write_text(context.reads['broker']['text'].replace(
                'token=token-original-one topic=881 transport=channel phase=confirmed',
                'token=token-argument-wrong topic=881 transport=channel phase=confirmed'))
            read=checked_read(path)
            observation=capture_observation(Cell(**context.descriptor['cell']),replay['evidence'],read,
                context.reads['adapter'],context.reads['host-records']['records'],context.reads['host-records'],capture_context=context)
        terminal=events(observation,'attempt_terminal')[0]
        self.assertEqual(terminal['token'],'token-argument-wrong')
        result=evaluate(*build_verdict_inputs(Cell(**context.descriptor['cell']),replay['evidence'],raw_observation=observation))
        self.assertIn(IDENTITY,result['reasons'])
        self.assertIn('receipt missing or outside 15-second window',result['reasons'])
        self.assertTrue(any('principal read differs' in item['code'] for item in context.diagnostics))

    def test_recognized_record_damage_cannot_disappear(self):
        from capture_context import broker_records
        lines=['TEST INJECT accepted topic=bad message_id=41001 kind=text source=test-inject',
               'TEST ATTEMPT token=x topic=881 transport=channel phase=reserved members=1 retired=0 elapsed_ms=bad',
               'TEST ATTEMPT token=x token=y topic=881 transport=channel phase=reserved members=1 retired=0 elapsed_ms=0',
               'TEST ATTEMPT token=x topic=881 transport=channel phase=reserved members='+ '9'*5000 +' retired=0 elapsed_ms=0',
               'TEST SINK reply topic=bad text="Held"']
        for line in lines:
            parsed=list(broker_records(line+'\n'))
            self.assertEqual(len(parsed),1)
            self.assertIsNone(parsed[0][2])
        self.assertEqual(list(broker_records('ordinary diagnostic\n')),[])
        with tempfile.TemporaryDirectory() as directory:
            path=Path(directory)/'records.jsonl'
            for data in (b'{"uuid":"one","uuid":"two"}\n',b'{"elapsed_ms":NaN}\n',b'['*1100):
                path.write_bytes(data+b'\n')
                self.assertEqual(checked_read(path,jsonl=True)['state'],'malformed')
            path.write_bytes(b'{"text":"'+b'\xff')
            self.assertEqual(checked_read(path,jsonl=True)['problems'],['byte:9: invalid UTF-8'])
            path.write_bytes(b'')
            self.assertEqual(checked_read(path)['state'],'complete')
        for value in (None,[],{'type':'user','message':False},{'type':'attachment','attachment':[]}):
            self.assertFalse(classify(value)['accept'])
            self.assertFalse(classify_fetch(value,dict(token='one',members=[]),set())['accept'])

    def test_authoring_helper_has_no_oracle_dependency(self):
        source=inspect.getsource(replay_fixture_support)
        for forbidden in ('verdict_fixture_support','verdict_core','from collect','from capture_context','author_witness','witnessed_verdict'):
            self.assertNotIn(forbidden,source)

    def test_explicit_identity_collapse_regressions(self):
        cases=['wrong-terminal-token','duplicate-host-delivery','wrong-recorded-fetch-row','wrong-host-session','stale-host-revision','duplicate-source-replacing-another']
        for name in cases:
            root=ROOT/'mutations'/name
            raw=load_capture(root)
            with self.subTest(name=name),tempfile.TemporaryDirectory() as directory:
                destination=Path(directory)
                export_replay_capture(raw,destination)
                clean=fresh_replay(destination)
                self.assertEqual(evaluate(*clean['inputs']),evaluate(*raw['inputs']))
                self.assertEqual(evaluate(*raw['inputs'])['status'],'FAIL')
                for o,base in ((raw['inputs'][2],root),(clean['inputs'][2],destination)):
                    reservations=events(o,'attempt_reserved')
                    host=events(o,'transcript_recorded')
                    if name=='wrong-terminal-token':
                        terminal=events(o,'attempt_terminal')[0]
                        self.assertNotEqual(reservations[0]['token'],terminal['token'])
                        self.assertEqual(reservations[0]['token'],host[0]['token'])
                        self.assertEqual(reservations[0]['token'],events(o,'receipt_accepted')[0]['token'])
                        self.assertEqual(terminal['token'],next(row.split('token=')[1].split()[0] for row in (base/'broker.log').read_text().splitlines() if 'phase=confirmed' in row))
                        self.assertEqual(['TOKEN' for _ in (reservations[0]['token'],terminal['token'])],['TOKEN','TOKEN'])
                    elif name=='duplicate-host-delivery':
                        records=[json.loads(v) for v in (base/'records.jsonl').read_text().splitlines()]
                        self.assertNotEqual(records[1]['uuid'],records[3]['uuid'])
                        self.assertEqual([host[0]['payload']['host_record_id'],host[2]['payload']['host_record_id']],[records[1]['uuid'],records[3]['uuid']])
                        self.assertNotEqual(host[0]['delivery_id'],host[2]['delivery_id'])
                        self.assertEqual(host[0]['members'],host[2]['members'])
                        sources=read_json(base/'context/injection.json')['message_ids']
                        self.assertNotEqual(sources[0],sources[1])
                        for source,record,reservation in zip(sources,records[1:3],reservations):
                            self.assertIn('message_id="'+str(source)+'"',record['message']['content'])
                            self.assertEqual(reservation['members'][0]['source_ids'],[str(source)])
                        summary=raw['evidence'] if base==root else read_json(base/'summary.json')
                        self.assertEqual(summary['message_ids'],sources)
                        self.assertEqual(summary['received'],{str(sources[0]):2,str(sources[1]):1})
                    elif name in ('wrong-recorded-fetch-row','stale-host-revision'):
                        produced=events(o,'fetch_result_produced')[0]
                        held=fetch_trailer(result_text(read_json(base/'held-fetch/response-1.json')['result']['content']))
                        record=[json.loads(v) for v in (base/'records.jsonl').read_text().splitlines()][2]
                        candidate=fetch_trailer(result_text(record['message']['content'][0]['content']))
                        key='record_id' if name=='wrong-recorded-fetch-row' else 'revision'
                        self.assertNotEqual(held['members'][0][key],candidate['members'][0][key])
                        self.assertEqual(held['members'][1],candidate['members'][1])
                        self.assertEqual(held['members'][0]['record_id'],produced['members'][0]['row_id'])
                        self.assertEqual(held['members'][0]['revision'],produced['members'][0]['revision']['value'])
                        self.assertEqual(produced['members'],reservations[0]['members'])
                        for trailer in (held,candidate):
                            for member in trailer['members']:
                                self.assertRegex(member['revision'],r'^[0-9a-f]{64}$')
                    elif name=='wrong-host-session':
                        scenario=read_json(base/'capture.json')['evidence']
                        record=[json.loads(v) for v in (base/'records.jsonl').read_text().splitlines()][1]
                        self.assertNotEqual(scenario['host_session_id'],record['sessionId'])
                        self.assertEqual(record['sessionId'],host[0]['scope']['host_session_id'])
                        self.assertEqual(scenario['host_session_id'],reservations[0]['scope']['host_session_id'])
                    else:
                        sources=read_json(base/'context/injection.json')['message_ids']
                        self.assertNotEqual(sources[0],sources[1])
                        self.assertEqual([str(v) for v in sources],[v['source_id'] for v in o['sources']])
                        self.assertEqual([v['members'][0]['source_ids'][0] for v in reservations],[str(v) for v in sources])
                        self.assertEqual(host[0]['members'][0]['source_ids'],host[1]['members'][0]['source_ids'])
                        summary=raw['evidence'] if base==root else read_json(base/'summary.json')
                        self.assertEqual(set(summary['received']),{str(v) for v in sources})
                        self.assertEqual(summary['received'][str(sources[0])],2)
                        self.assertEqual(summary['received'][str(sources[1])],0)


if __name__=='__main__':
    unittest.main()
