package c3types

import (
	"encoding/json"
	"reflect"
	"strings"
	"testing"
)

// liveQueueLine is a VERBATIM line lifted from a real .jsonl queue file. It is
// the format that is already on users' disks, so it is the thing this package
// is not allowed to break. Kept as an opaque string on purpose: it must never
// be regenerated by marshaling the current structs, because that would make the
// test agree with whatever the code does today instead of with what shipped.
const liveQueueLine = `{"Channel":"telegram","ChatID":-1003990699908,"TopicID":3826,"MessageID":6675,"Sender":{"UserID":85720317,"Username":"skarthi"},"Text":"hello","Attachments":null,"ReplyTo":{"MessageID":3826,"User":{"UserID":1205071350,"Username":"somebot"},"Text":""},"Timestamp":"2026-07-25T14:44:04Z"}`

// TestJSONTagNamesAreFrozenToGoFieldNames is the enforcement mechanism for the
// wire/on-disk format freeze, and it is deliberately blunt: EVERY exported field
// of every type reachable from the roots below must carry an explicit json tag
// whose name is BYTE-IDENTICAL to the Go field name.
//
// Before those tags existed, encoding/json fell back to the Go field name, so
// the Go identifiers silently WERE the on-disk queue format and the IPC wire
// format. Renaming a field — or "tidying" a tag to snake_case, which looks like
// hygiene and is in fact the bug — would rewrite the format underneath records
// that are already queued on disk and adapters that are already parsing them.
// This test makes that a build failure instead of a silent data-loss event.
//
// If you are here because you added a field: add the tag with the identical
// name. If you are here because you renamed one: the tag must NOT follow the
// rename — the old key is the contract.
func TestJSONTagNamesAreFrozenToGoFieldNames(t *testing.T) {
	roots := []reflect.Type{
		reflect.TypeOf(Inbound{}), reflect.TypeOf(InboundEvent{}), reflect.TypeOf(SystemEvent{}),
		reflect.TypeOf(HealthEvent{}), reflect.TypeOf(PollResult{}), reflect.TypeOf(PollOptionTally{}),
		reflect.TypeOf(ReactionEvent{}), reflect.TypeOf(CallbackEvent{}), reflect.TypeOf(Sender{}),
		reflect.TypeOf(Attachment{}), reflect.TypeOf(ReplyContext{}), reflect.TypeOf(Outbound{}),
		reflect.TypeOf(Button{}), reflect.TypeOf(EditArgs{}), reflect.TypeOf(EditResult{}),
		reflect.TypeOf(ReactArgs{}), reflect.TypeOf(ReadbackArgs{}), reflect.TypeOf(VoicePayload{}),
		reflect.TypeOf(Capabilities{}), reflect.TypeOf(InboundCaps{}), reflect.TypeOf(StreamCaps{}),
		reflect.TypeOf(MediaItem{}), reflect.TypeOf(PollSpec{}), reflect.TypeOf(Alteration{}),
	}
	seen := map[reflect.Type]bool{}
	var walk func(reflect.Type)
	walk = func(rt reflect.Type) {
		for rt.Kind() == reflect.Ptr || rt.Kind() == reflect.Slice || rt.Kind() == reflect.Array {
			rt = rt.Elem()
		}
		if rt.Kind() != reflect.Struct || seen[rt] {
			return
		}
		seen[rt] = true
		for i := 0; i < rt.NumField(); i++ {
			f := rt.Field(i)
			if f.PkgPath != "" { // unexported: never serialized, nothing to freeze
				continue
			}
			tag, ok := f.Tag.Lookup("json")
			if !ok {
				t.Errorf("%s.%s has NO json tag — without one the Go field name silently becomes the wire key", rt.Name(), f.Name)
				continue
			}
			name := tag
			if i := strings.Index(tag, ","); i >= 0 {
				name = tag[:i]
			}
			if name != f.Name {
				t.Errorf("%s.%s is tagged json:%q — the tag name MUST be byte-identical to the Go field name (%q). Renaming the key breaks every record already on disk.",
					rt.Name(), f.Name, tag, f.Name)
			}
			walk(f.Type)
		}
	}
	for _, rt := range roots {
		walk(rt)
	}
}

// TestInboundDecodesRealQueuedLine pins the actual on-disk contract end to end:
// a line written by a build that predates the json tags must still decode into
// every field it names, and re-encoding must not drop or rename any of them.
func TestInboundDecodesRealQueuedLine(t *testing.T) {
	var in Inbound
	if err := json.Unmarshal([]byte(liveQueueLine), &in); err != nil {
		t.Fatalf("a real queued line no longer decodes: %v", err)
	}
	switch {
	case in.Channel != "telegram":
		t.Errorf("Channel = %q, want telegram", in.Channel)
	case in.ChatID != -1003990699908:
		t.Errorf("ChatID = %d", in.ChatID)
	case in.TopicID == nil || *in.TopicID != 3826:
		t.Errorf("TopicID = %v", in.TopicID)
	case in.MessageID != 6675:
		t.Errorf("MessageID = %d", in.MessageID)
	case in.Sender.UserID != 85720317 || in.Sender.Username != "skarthi":
		t.Errorf("Sender = %+v", in.Sender)
	case in.ReplyTo == nil || in.ReplyTo.MessageID != 3826 || in.ReplyTo.User.UserID != 1205071350:
		t.Errorf("ReplyTo = %+v", in.ReplyTo)
	case in.Timestamp.IsZero():
		t.Errorf("Timestamp did not decode")
	}
	// A pre-versioning record carries no "V" key at all; absent MUST read as
	// version 1, which is what a zero V means. It must not decode as "unknown".
	if in.V != 0 {
		t.Errorf("V = %d on a legacy line, want 0 (== version 1)", in.V)
	}
	if in.ConvKind != "" {
		t.Errorf("ConvKind = %q on a legacy line, want empty (channel did not say)", in.ConvKind)
	}

	// Re-encode: every key the original line carried must still be present and
	// spelled identically.
	out, err := json.Marshal(in)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	for _, key := range []string{
		`"Channel":`, `"ChatID":`, `"TopicID":`, `"MessageID":`, `"Sender":`, `"UserID":`,
		`"Username":`, `"Text":`, `"Attachments":`, `"ReplyTo":`, `"User":`, `"Timestamp":`,
	} {
		if !strings.Contains(string(out), key) {
			t.Errorf("re-encoded record lost key %s — this silently orphans queued messages\ngot: %s", key, out)
		}
	}
}

// TestInboundVersionAndConvKindOmitEmpty pins the presence semantics of the two
// fields added alongside the freeze. Both MUST be omitempty: an unconditional
// "V":0 / "ConvKind":"" on every written record would itself be an unannounced
// format change — exactly the thing being prevented.
func TestInboundVersionAndConvKindOmitEmpty(t *testing.T) {
	zero, err := json.Marshal(Inbound{Channel: "telegram", ChatID: -100, MessageID: 1})
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if strings.Contains(string(zero), "V") || strings.Contains(string(zero), "ConvKind") {
		t.Fatalf("unset V/ConvKind must be OMITTED so pre-existing records stay byte-identical, got %s", zero)
	}

	set, err := json.Marshal(Inbound{Channel: "telegram", ChatID: -100, MessageID: 2, V: InboundRecordVersion, ConvKind: "group"})
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !strings.Contains(string(set), `"V":1`) || !strings.Contains(string(set), `"ConvKind":"group"`) {
		t.Fatalf("set V/ConvKind must serialize under their exact names, got %s", set)
	}

	// A record from a NEWER writer (higher V, plus a key this build has never
	// heard of) must still decode. A mixed-version install sharing one queue dir
	// is normal; hard-failing there would turn a cosmetic skew into lost
	// messages, which is the opposite of what versioning is for.
	var future Inbound
	if err := json.Unmarshal([]byte(`{"Channel":"telegram","ChatID":-100,"MessageID":3,"Text":"from the future","V":99,"SomethingNew":{"a":1}}`), &future); err != nil {
		t.Fatalf("a higher V / unknown key must NOT be rejected: %v", err)
	}
	if future.V != 99 || future.Text != "from the future" {
		t.Fatalf("future record = %+v, want V=99 and its text preserved", future)
	}
}

func TestInboundConstruct(t *testing.T) {
	id := int64(281)
	in := Inbound{
		Channel:   "telegram",
		ChatID:    -100,
		TopicID:   &id,
		MessageID: 868,
		Sender:    Sender{UserID: 42, Username: "x"},
		Text:      "hi",
	}
	if in.TopicID == nil || *in.TopicID != 281 {
		t.Errorf("TopicID round-trip: %+v", in.TopicID)
	}
}

// TestInboundDrainedFromSerialization pins the DrainedFrom omitempty contract:
// an organic (empty) DrainedFrom is OMITTED from the JSON (so every pre-drain
// marshal stays byte-identical); an old JSONL line without the field unmarshals
// to ""; and a set DrainedFrom round-trips.
func TestInboundDrainedFromSerialization(t *testing.T) {
	// Organic line: DrainedFrom empty ⇒ key omitted.
	organic, err := json.Marshal(Inbound{Channel: "telegram", ChatID: -100, MessageID: 1, Text: "hi"})
	if err != nil {
		t.Fatalf("marshal organic: %v", err)
	}
	if strings.Contains(string(organic), "DrainedFrom") {
		t.Fatalf("organic marshal must omit DrainedFrom, got %s", organic)
	}

	// Old JSONL line without the field ⇒ unmarshals to "".
	var old Inbound
	if err := json.Unmarshal([]byte(`{"Channel":"telegram","ChatID":-100,"MessageID":2,"Text":"legacy"}`), &old); err != nil {
		t.Fatalf("unmarshal legacy: %v", err)
	}
	if old.DrainedFrom != "" || old.MessageID != 2 {
		t.Fatalf("legacy line = %+v, want DrainedFrom empty / MessageID 2", old)
	}

	// A set DrainedFrom round-trips.
	drained, err := json.Marshal(Inbound{Channel: "telegram", ChatID: -100, MessageID: 3, DrainedFrom: "telegram__-100__42"})
	if err != nil {
		t.Fatalf("marshal drained: %v", err)
	}
	if !strings.Contains(string(drained), `"DrainedFrom":"telegram__-100__42"`) {
		t.Fatalf("set DrainedFrom must serialize, got %s", drained)
	}
	var back Inbound
	if err := json.Unmarshal(drained, &back); err != nil {
		t.Fatalf("unmarshal drained: %v", err)
	}
	if back.DrainedFrom != "telegram__-100__42" {
		t.Fatalf("DrainedFrom round-trip = %q, want telegram__-100__42", back.DrainedFrom)
	}
}

func TestReplyArgsAlias(t *testing.T) {
	// ReplyArgs = Outbound, exercise type-alias equivalence.
	id := int64(1)
	r := ReplyArgs{Channel: "telegram", ChatID: -100, TopicID: &id, Text: "hi"}
	o := Outbound(r)
	if o.Text != "hi" {
		t.Errorf("alias roundtrip lost field: %+v", o)
	}
}
